// Product Catalog Data & Configuration for Mobile Station
const STORE_CONFIG = {
  primaryPhone: "919876543210", // Mobile Station Retail WhatsApp
  stores: [
    {
      id: "mobile-station",
      name: "Mobile Station",
      tagline: "Your Ultimate Smartphone & Gadget Destination",
      address: "Garud Complex, In front of Sony Novelty",
      phone: "+91 98765 43210",
      whatsapp: "919876543210",
      type: "Retail Showroom & 30-Min Fast Repair Hub",
      timing: "10:00 AM - 9:30 PM (Open All 7 Days)",
      badge: "Flagship Retail Showroom",
      features: ["Brand New 5G Smartphones", "Certified Pre-Owned Devices", "On-Spot Screen & Battery Repair", "0% Easy EMI & Instant Exchange"]
    }
  ]
};

const CATEGORIES = [
  { id: "all", name: "All Products", icon: "📱" },
  { id: "apple", name: "Apple iPhones", icon: "🍏" },
  { id: "flagship", name: "Flagship 5G", icon: "👑" },
  { id: "budget", name: "Budget Champions", icon: "🔥" },
  { id: "refurbished", name: "Certified Pre-Owned", icon: "♻️" },
  { id: "smartwatches", name: "Smartwatches", icon: "⌚" },
  { id: "audio", name: "Earbuds & Audio", icon: "🎧" },
  { id: "accessories", name: "Fast Chargers & Cases", icon: "⚡" }
];

const BRANDS = ["All", "Apple", "Samsung", "OnePlus", "Vivo", "Xiaomi", "Realme", "Boat", "Anker"];

const PRODUCTS = [
  {
    id: "prod-001",
    name: "Apple iPhone 16 Pro Max",
    brand: "Apple",
    category: "apple",
    subCategory: "flagship",
    price: 144900,
    originalPrice: 159900,
    discountPercent: 9,
    rating: 4.9,
    reviewsCount: 384,
    badge: "🔥 Best Seller",
    isHotDeal: true,
    condition: "Brand New Sealed Box Pack",
    warranty: "1 Year Official Apple Warranty",
    image: "https://images.unsplash.com/photo-1695048133142-1a20484d2569?auto=format&fit=crop&w=600&q=80",
    colors: ["Desert Titanium", "Natural Titanium", "White Titanium", "Black Titanium"],
    storageOptions: ["256GB", "512GB", "1TB"],
    specs: {
      display: "6.9\" Super Retina XDR OLED (120Hz ProMotion)",
      processor: "Apple A18 Pro Bionic Chip (3nm)",
      camera: "48MP Fusion + 48MP Ultra-Wide + 12MP 5x Telephoto",
      battery: "Up to 33 hours video playback, MagSafe Fast Charging",
      os: "iOS 18 with Apple Intelligence"
    },
    inStock: true,
    emiStart: "₹6,990/mo"
  },
  {
    id: "prod-002",
    name: "Samsung Galaxy S24 Ultra 5G",
    brand: "Samsung",
    category: "flagship",
    subCategory: "flagship",
    price: 119999,
    originalPrice: 134999,
    discountPercent: 11,
    rating: 4.8,
    reviewsCount: 295,
    badge: "⭐ Galaxy AI",
    isHotDeal: true,
    condition: "Brand New Sealed Box Pack",
    warranty: "1 Year Samsung India Warranty",
    image: "https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?auto=format&fit=crop&w=600&q=80",
    colors: ["Titanium Gray", "Titanium Black", "Titanium Violet", "Titanium Yellow"],
    storageOptions: ["12GB/256GB", "12GB/512GB", "12GB/1TB"],
    specs: {
      display: "6.8\" Dynamic AMOLED 2X, 2600 nits Peak, Gorilla Armor",
      processor: "Snapdragon 8 Gen 3 for Galaxy",
      camera: "200MP Quad Camera + 100x Space Zoom with AI",
      battery: "5000 mAh with 45W Fast Charging & S-Pen Included",
      os: "Android 14 (One UI 6.1 with 7 Years OS Updates)"
    },
    inStock: true,
    emiStart: "₹5,750/mo"
  },
  {
    id: "prod-003",
    name: "OnePlus 12 5G (Flowy Emerald)",
    brand: "OnePlus",
    category: "flagship",
    subCategory: "flagship",
    price: 64999,
    originalPrice: 69999,
    discountPercent: 7,
    rating: 4.7,
    reviewsCount: 182,
    badge: "⚡ 100W SuperVOOC",
    isHotDeal: false,
    condition: "Brand New Sealed Box",
    warranty: "1 Year OnePlus Warranty",
    image: "https://images.unsplash.com/photo-1598327105666-5b89351aff97?auto=format&fit=crop&w=600&q=80",
    colors: ["Flowy Emerald", "Silky Black", "Glacial White"],
    storageOptions: ["12GB/256GB", "16GB/512GB"],
    specs: {
      display: "6.82\" 2K 120Hz ProXDR Display, 4500 nits peak",
      processor: "Snapdragon 8 Gen 3 Flagship Chipset",
      camera: "4th Gen Hasselblad Camera (50MP Sony LYT-808)",
      battery: "5400 mAh, 100W Wired + 50W Wireless AIRVOOC",
      os: "OxygenOS 14 based on Android 14"
    },
    inStock: true,
    emiStart: "₹3,120/mo"
  },
  {
    id: "prod-004",
    name: "Vivo V40 Pro 5G (ZEISS Portrait)",
    brand: "Vivo",
    category: "flagship",
    subCategory: "budget",
    price: 49999,
    originalPrice: 55999,
    discountPercent: 11,
    rating: 4.6,
    reviewsCount: 145,
    badge: "📸 ZEISS Optics",
    isHotDeal: true,
    condition: "Brand New Sealed",
    warranty: "1 Year Vivo India Warranty",
    image: "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=600&q=80",
    colors: ["Ganges Blue", "Titanium Grey"],
    storageOptions: ["8GB/256GB", "12GB/512GB"],
    specs: {
      display: "6.78\" 1.5K 3D Curved AMOLED, 120Hz, 4500 nits",
      processor: "MediaTek Dimensity 9200+ (4nm Flagship)",
      camera: "50MP ZEISS Main + 50MP ZEISS Telephoto + 50MP Ultra-Wide",
      battery: "5500 mAh BlueVolt Battery + 80W FlashCharge",
      os: "Funtouch OS 14 (Android 14)"
    },
    inStock: true,
    emiStart: "₹2,399/mo"
  },
  {
    id: "prod-005",
    name: "Apple iPhone 15 (Dynamic Island)",
    brand: "Apple",
    category: "apple",
    subCategory: "flagship",
    price: 65999,
    originalPrice: 79900,
    discountPercent: 17,
    rating: 4.8,
    reviewsCount: 520,
    badge: "🏷️ Big Price Drop",
    isHotDeal: true,
    condition: "Brand New Sealed Box",
    warranty: "1 Year Official Apple Warranty",
    image: "https://images.unsplash.com/photo-1592750475338-74b7b21085ab?auto=format&fit=crop&w=600&q=80",
    colors: ["Blue", "Pink", "Yellow", "Green", "Black"],
    storageOptions: ["128GB", "256GB", "512GB"],
    specs: {
      display: "6.1\" Super Retina XDR OLED with Dynamic Island",
      processor: "A16 Bionic chip with 5-core GPU",
      camera: "48MP Main Camera with 2x Telephoto + 12MP Ultra-Wide",
      battery: "All-day battery life, USB-C Port",
      os: "iOS 18 Ready"
    },
    inStock: true,
    emiStart: "₹3,170/mo"
  },
  {
    id: "prod-006",
    name: "Redmi Note 13 Pro+ 5G (Fusion Purple)",
    brand: "Xiaomi",
    category: "budget",
    subCategory: "budget",
    price: 29999,
    originalPrice: 33999,
    discountPercent: 12,
    rating: 4.5,
    reviewsCount: 210,
    badge: "🌟 200MP OIS",
    isHotDeal: false,
    condition: "Brand New Sealed",
    warranty: "1 Year Xiaomi India Warranty",
    image: "https://images.unsplash.com/photo-1580910051074-3eb694886505?auto=format&fit=crop&w=600&q=80",
    colors: ["Fusion Purple", "Fusion Black", "Fusion White"],
    storageOptions: ["8GB/256GB", "12GB/512GB"],
    specs: {
      display: "6.67\" 1.5K 120Hz 3D Curved AMOLED with Victus Glass",
      processor: "MediaTek Dimensity 7200 Ultra 5G",
      camera: "200MP Samsung ISOCELL HP3 with OIS + 8MP + 2MP",
      battery: "5000 mAh with 120W HyperCharge (0-100% in 19 mins)",
      os: "Xiaomi HyperOS (Android 14)"
    },
    inStock: true,
    emiStart: "₹1,440/mo"
  },
  {
    id: "prod-007",
    name: "Realme 13+ 5G (Speed Green)",
    brand: "Realme",
    category: "budget",
    subCategory: "budget",
    price: 22999,
    originalPrice: 25999,
    discountPercent: 12,
    rating: 4.5,
    reviewsCount: 168,
    badge: "⚡ 80W Fast Charge",
    isHotDeal: false,
    condition: "Brand New Sealed",
    warranty: "1 Year Realme Warranty",
    image: "https://images.unsplash.com/photo-1565849904461-04a58ad377e0?auto=format&fit=crop&w=600&q=80",
    colors: ["Speed Green", "Victory Gold", "Dark Purple"],
    storageOptions: ["8GB/128GB", "8GB/256GB", "12GB/256GB"],
    specs: {
      display: "6.67\" 120Hz OLED Esports Display, 2000 nits",
      processor: "MediaTek Dimensity 7300 Energy 5G (4nm)",
      camera: "50MP Sony LYT-600 OIS Camera",
      battery: "5000 mAh + 80W Ultra Charge",
      os: "Realme UI 5.0 (Android 14)"
    },
    inStock: true,
    emiStart: "₹1,110/mo"
  },
  {
    id: "prod-008",
    name: "Apple iPhone 13 (Certified Pre-Owned 100% Battery)",
    brand: "Apple",
    category: "refurbished",
    subCategory: "refurbished",
    price: 36999,
    originalPrice: 59900,
    discountPercent: 38,
    rating: 4.9,
    reviewsCount: 412,
    badge: "💎 Certified Grade A+",
    isHotDeal: true,
    condition: "Certified Pre-Owned (32-Point Quality Inspected, 100% Original)",
    warranty: "6 Months Mobile Station Replacement Warranty",
    image: "https://images.unsplash.com/photo-1575695342320-d2d2d2f9b73f?auto=format&fit=crop&w=600&q=80",
    colors: ["Midnight", "Starlight", "Blue", "Pink"],
    storageOptions: ["128GB", "256GB"],
    specs: {
      display: "6.1\" Super Retina XDR OLED Display (Scratchless)",
      processor: "A15 Bionic chip (Blazing Fast)",
      camera: "Dual 12MP Camera with Cinematic mode 4K",
      battery: "Tested 95%+ Battery Health, Original Parts Guaranteed",
      os: "iOS 18 Ready"
    },
    inStock: true,
    emiStart: "₹1,780/mo"
  },
  {
    id: "prod-009",
    name: "Samsung Galaxy S22 5G (Certified Pre-Owned)",
    brand: "Samsung",
    category: "refurbished",
    subCategory: "refurbished",
    price: 27999,
    originalPrice: 72999,
    discountPercent: 62,
    rating: 4.7,
    reviewsCount: 189,
    badge: "🔥 62% OFF",
    isHotDeal: true,
    condition: "Certified Refurbished (Flawless Grade A+)",
    warranty: "6 Months Mobile Station Warranty",
    image: "https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?auto=format&fit=crop&w=600&q=80",
    colors: ["Phantom Black", "Green", "Phantom White"],
    storageOptions: ["8GB/128GB", "8GB/256GB"],
    specs: {
      display: "6.1\" Dynamic AMOLED 2X (120Hz)",
      processor: "Snapdragon 8 Gen 1",
      camera: "50MP Triple Pro Camera + 30X Space Zoom",
      battery: "3700 mAh + 25W Fast Charging",
      os: "One UI 6.1 (Android 14)"
    },
    inStock: true,
    emiStart: "₹1,340/mo"
  },
  {
    id: "prod-010",
    name: "Apple AirPods Pro (2nd Gen with USB-C & ANC)",
    brand: "Apple",
    category: "audio",
    subCategory: "accessories",
    price: 20999,
    originalPrice: 24900,
    discountPercent: 16,
    rating: 4.9,
    reviewsCount: 310,
    badge: "🎧 Active Noise Cancelling",
    isHotDeal: false,
    condition: "Brand New Sealed Box",
    warranty: "1 Year Official Apple Warranty",
    image: "https://images.unsplash.com/photo-1600294037681-c80b4cb5b434?auto=format&fit=crop&w=600&q=80",
    colors: ["White"],
    storageOptions: ["MagSafe USB-C Case"],
    specs: {
      display: "Apple H2 Silicon Chip with Personalized Spatial Audio",
      processor: "Up to 2x more Active Noise Cancellation + Adaptive Audio",
      camera: "Touch control volume slider on stem",
      battery: "Up to 6 hours listening (30 hours with MagSafe Case)",
      os: "Universal iOS / Android Support"
    },
    inStock: true,
    emiStart: "₹1,010/mo"
  },
  {
    id: "prod-011",
    name: "boAt Airdopes 141 ANC TWS Earbuds",
    brand: "Boat",
    category: "audio",
    subCategory: "accessories",
    price: 1499,
    originalPrice: 4490,
    discountPercent: 67,
    rating: 4.4,
    reviewsCount: 890,
    badge: "💥 67% OFF",
    isHotDeal: true,
    condition: "Brand New Box Pack",
    warranty: "1 Year boAt Warranty",
    image: "https://images.unsplash.com/photo-1590658268037-6bf12165a8df?auto=format&fit=crop&w=600&q=80",
    colors: ["Active Black", "Cider Cyan", "Gunmetal Grey"],
    storageOptions: ["Standard"],
    specs: {
      display: "32dB Active Noise Cancellation (ANC)",
      processor: "42 Hours Total Playback with ASAP Fast Charge",
      camera: "ENx Quad Mics for Crystal Clear Calls",
      battery: "10 mins charge = 150 mins playtime",
      os: "Bluetooth v5.3"
    },
    inStock: true,
    emiStart: "N/A"
  },
  {
    id: "prod-012",
    name: "Samsung Galaxy Watch6 Bluetooth 44mm",
    brand: "Samsung",
    category: "smartwatches",
    subCategory: "accessories",
    price: 18999,
    originalPrice: 33999,
    discountPercent: 44,
    rating: 4.7,
    reviewsCount: 142,
    badge: "⌚ Health & ECG Track",
    isHotDeal: true,
    condition: "Brand New Sealed Box",
    warranty: "1 Year Samsung India Warranty",
    image: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=600&q=80",
    colors: ["Graphite", "Silver"],
    storageOptions: ["44mm Bluetooth", "44mm LTE"],
    specs: {
      display: "1.5\" Super AMOLED Sapphire Crystal Glass",
      processor: "Exynos W930 Dual Core 1.4GHz",
      camera: "BioActive Sensor (Sleep Coaching, ECG, BP, Heart Rate)",
      battery: "Up to 40 Hours + Fast Wireless Charge",
      os: "Wear OS Powered by Samsung"
    },
    inStock: true,
    emiStart: "₹910/mo"
  },
  {
    id: "prod-013",
    name: "Apple 20W USB-C Fast Power Adapter",
    brand: "Apple",
    category: "accessories",
    subCategory: "accessories",
    price: 1699,
    originalPrice: 1900,
    discountPercent: 11,
    rating: 4.9,
    reviewsCount: 760,
    badge: "⚡ 100% Original Apple",
    isHotDeal: false,
    condition: "Brand New Box Pack",
    warranty: "1 Year Apple Warranty",
    image: "https://images.unsplash.com/photo-1583863788434-e58a36330cf0?auto=format&fit=crop&w=600&q=80",
    colors: ["White"],
    storageOptions: ["20W USB-C"],
    specs: {
      display: "Original Genuine Apple 20W Fast Charger",
      processor: "Supports Power Delivery (PD 3.0)",
      camera: "Charges iPhone 50% in just 30 mins",
      battery: "Over-voltage & overheating protection",
      os: "All iPhones, iPads, Apple Watches"
    },
    inStock: true,
    emiStart: "N/A"
  },
  {
    id: "prod-014",
    name: "Anker 65W GaN III 3-Port Fast Charger",
    brand: "Anker",
    category: "accessories",
    subCategory: "accessories",
    price: 3499,
    originalPrice: 4999,
    discountPercent: 30,
    rating: 4.8,
    reviewsCount: 230,
    badge: "🔋 GaN Fast Tech",
    isHotDeal: false,
    condition: "Brand New Box Pack",
    warranty: "18 Months Anker Replacement Warranty",
    image: "https://images.unsplash.com/photo-1541643600914-78b084683601?auto=format&fit=crop&w=600&q=80",
    colors: ["Black", "White"],
    storageOptions: ["65W 3-Port"],
    specs: {
      display: "2x USB-C + 1x USB-A Simultaneous Fast Charging",
      processor: "Charges Laptops, MacBooks, iPhones, Samsung phones at full speed",
      camera: "GaN III Technology with ActiveShield 2.0 temperature control",
      battery: "Compact foldable plug design",
      os: "Universal Compatibility"
    },
    inStock: true,
    emiStart: "N/A"
  },
  {
    id: "prod-015",
    name: "Premium Military-Grade MagSafe Armor Case + 9H Glass Combo",
    brand: "Mobile Station Exclusive",
    category: "accessories",
    subCategory: "accessories",
    price: 699,
    originalPrice: 1499,
    discountPercent: 53,
    rating: 4.9,
    reviewsCount: 540,
    badge: "🛡️ Heavy Duty Combo",
    isHotDeal: true,
    condition: "Brand New",
    warranty: "Fitment & Replacement Guarantee",
    image: "https://images.unsplash.com/photo-1584438784894-089d6a62b8fa?auto=format&fit=crop&w=600&q=80",
    colors: ["Translucent Matte", "Smoky Black", "Navy Blue"],
    storageOptions: ["Available for All iPhone & Android Models"],
    specs: {
      display: "Strong N52 Magnetic Ring for instant MagSafe latching",
      processor: "Air-cushioned corners with 10ft drop tested protection",
      camera: "Raised 1.5mm lips for Camera Lens & Screen safety",
      battery: "Includes 9H Hardness Edge-to-Edge Tempered Glass",
      os: "Free on-spot installation at Mobile Station store"
    },
    inStock: true,
    emiStart: "N/A"
  }
];

const REPAIR_SERVICES = [
  {
    id: "rep-screen",
    title: "Broken Screen & Display Replacement",
    icon: "📱",
    description: "Original OLED / AMOLED & High Grade IPS displays with touch responsiveness & true-tone support.",
    turnaround: "30 - 45 Minutes",
    warranty: "6 Months Warranty",
    startingPrice: "₹1,199"
  },
  {
    id: "rep-battery",
    title: "Battery Replacement & Health Boost",
    icon: "🔋",
    description: "100% capacity original grade batteries with genuine thermal sensors and fast charge safety.",
    turnaround: "20 Minutes",
    warranty: "6 Months Warranty",
    startingPrice: "₹799"
  },
  {
    id: "rep-water",
    title: "Water Damage & Liquid Recovery",
    icon: "💧",
    description: "Ultrasonic chemical bath PCB cleaning, short circuit repair, and chip-level motherboard revival.",
    turnaround: "Same Day",
    warranty: "Tested Diagnostics",
    startingPrice: "₹499"
  },
  {
    id: "rep-camera",
    title: "Camera Lens & Sensor Repair",
    icon: "📷",
    description: "Fix blurry cameras, cracked outer glass, shaking OIS stabilization, or black camera issues.",
    turnaround: "45 Minutes",
    warranty: "3 Months Warranty",
    startingPrice: "₹699"
  },
  {
    id: "rep-port",
    title: "Charging Port & Speaker Fix",
    icon: "⚡",
    description: "Fix loose charging cables, slow charging, mic issues, ear speaker noise, and loud speaker distortion.",
    turnaround: "25 Minutes",
    warranty: "3 Months Warranty",
    startingPrice: "₹399"
  },
  {
    id: "rep-software",
    title: "Software, Bootloop & Unlocking",
    icon: "💻",
    description: "OS flashing, pattern/PIN recovery, hanging fix, iCloud / Google account guidance, and data transfer.",
    turnaround: "30 Minutes",
    warranty: "100% Safe",
    startingPrice: "₹299"
  }
];

const CUSTOMER_REVIEWS = [
  {
    id: 1,
    name: "Rajesh Sharma",
    location: "Garud Complex, Regular Customer",
    rating: 5,
    date: "2 days ago",
    product: "Apple iPhone 16 Pro Max",
    comment: "Mobile Station se best deal kahin nahi milti! Amazon se bhi saste me sealed pack iPhone 16 Pro Max mil gaya aur free tempered glass bhi lagakar diya. Ekdum trustworthy shop.",
    verified: true
  },
  {
    id: 2,
    name: "Neha Verma",
    location: "Garud Complex, Showroom Customer",
    rating: 5,
    date: "1 week ago",
    product: "Samsung Galaxy S24 Ultra",
    comment: "WhatsApp par direct baat ki, inhone turant color options aur price quotes bhej diye. Shop par jakar 10 minute me purchase kar liya. Mobile Station customer service is top notch!",
    verified: true
  },
  {
    id: 3,
    name: "Amit Patel",
    location: "Corporate Client",
    rating: 5,
    date: "2 weeks ago",
    product: "Bulk Mobile Accessories & Fast Chargers",
    comment: "Mobile Station (Garud Complex) se genuine cases and 65W GaN fast chargers mangwaye the. Rates market se bhi best hain aur delivery instant.",
    verified: true
  },
  {
    id: 4,
    name: "Vikram Chauhan",
    location: "Mobile Repair Customer",
    rating: 5,
    date: "3 weeks ago",
    product: "iPhone 13 Display & Battery Replacement",
    comment: "Display toot gaya tha, Mobile Station par 30 minutes me original OLED screen fit karke diya with warranty. Phone bilkul naya jaisa chal raha hai!",
    verified: true
  },
  {
    id: 5,
    name: "Pooja Deshmukh",
    location: "Student",
    rating: 5,
    date: "A month ago",
    product: "iPhone 13 Certified Pre-Owned",
    comment: "Pre-owned iPhone 13 liya 100% battery health ke sath. Ek bhi scratch nahi tha aur 6 months shop warranty bhi di. Super happy!",
    verified: true
  }
];
